<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class H5PAddCPEditorOneTwentySixTranslationSeeder extends Seeder
{
    public function run()
    {
        $lib = DB::table('h5p_libraries')
            ->where(['name' => 'H5PEditor.CoursePresentation', 'major_version' => 1, 'minor_version' => 26])
            ->first();

        if (empty($lib)) {
            return;
        }

        $libId = $lib->id;

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'ar'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'ar',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "هل تريد بالتأكيد حذف هذه الشريحة؟", "sortSlide": "حرّك الشريحة :dir", "backgroundSlide": "خلفية الشريحة", "removeSlide": "حذف الشريحة", "cloneSlide": "نسخ الشريحة", "newSlide": "أضف شريحة جديدة", "insertElement": "انقر واسحب للإدراج :type", "newKeyword": "كلمة مفتاحية جديدة", "save": "حفظ", "confirmRemoveElement": "هل تريد بالتأكيد حذف هذا العنصر؟", "cancel": "إلغاء", "done": "تم", "remove": "الحذف", "edit": "تحرير", "keywordsTip": "اسحب الكلمات الرئيسية باستخدام الزرين الموجودين في الأعلى.", "loading": "يجري التحميل...", "slides": "شرائح", "element": "عنصر", "resetToDefault": "إعادة الضبط للوضع الافتراضي", "resetToTemplate": "إعادة الضبط لوضع القالب", "slideBackground": "خلفية الشريحة", "setImageBackground": "خلفية الصورة", "setColorFillBackground": "تعبئة ألوان الخلفية", "activeSurfaceWarning": "هل أنت متأكد من رغبتك في تفعيل وضع السطح النشط؟ لا يمكن التراجع عن هذا الإجراء.", "template": "القالب", "templateDescription": "سيتم تطبيقه على جميع الشرائح التي لم يتم تغيير \\":currentSlide\\" إعداداتها.", "currentSlide": "الشريحة الحالية", "currentSlideDescription": "سيتم تطبيقه على الشريحة الحالية فقط، وتجاوز أية \\":template\\" إعدادات.", "showTitles": "أظهر العناوين", "alwaysShow": "أظهر دائمًا", "autoHide": "إخفاء تلقائي", "ok": "حسنًا", "slide": "شريحة", "opacity": "ضبابية", "goToSlide": "اذهب إلى الشريحة", "expandBreadcrumbButtonLabel": "عودة", "collapseBreadcrumbButtonLabel": "إغلاق شريط التنقل"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'bg'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'bg',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Наистина ли искате да изтриете този слайд?", "sortSlide": "Преместване на слайда :dir", "backgroundSlide": "Фон на слайда", "removeSlide": "Изтриване на слайда", "cloneSlide": "Клониране на слайда", "newSlide": "Добавяне на нов слайд", "insertElement": "Кликнете и плъзнете, за да поставите: тип", "newKeyword": "Нова ключова дума", "save": "Запазване", "confirmRemoveElement": "Сигурни ли сте, че искате да премахнете този елемент?", "cancel": "Отказ", "done": "Завършено", "remove": "Премахване", "edit": "Редактиране", "keywordsTip": "Плъзнете в ключовите думи като използате двата бутона по-горе.", "loading": "Зареждане...", "slides": "Слайдове", "element": "елемент", "resetToDefault": "Нулиране към първоналано зададеното", "resetToTemplate": "Нулиране към шаблона", "slideBackground": "Фон на слайда", "setImageBackground": "Фон на изображението", "setColorFillBackground": "Фон за попълване на цвят", "activeSurfaceWarning": "Наистина ли искате да активирате режима Active Surface? Това действие не може да бъде отменено.", "template": "Шаблон", "templateDescription": "Ще бъдат приложени към всички слайдове, които не се заменят с настройки на: \\":currentSlide\\".", "currentSlide": "Този слайд", "currentSlideDescription": "Ще бъде приложено само към този слайд и ще отмени всички \\":шаблони\\" настройки.", "showTitles": "Покажи заглавията", "alwaysShow": "Показвай винаги", "autoHide": "Автоматично скриване", "ok": "OK", "slide": "Слайд", "opacity": "Непрозрачност", "goToSlide": "Отиди към слайда", "expandBreadcrumbButtonLabel": "Върни се", "collapseBreadcrumbButtonLabel": "Затваряне на навигацията"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'bs'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'bs',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Jeste li sigurni da želite obrisati ovaj slajd?", "sortSlide": "Sortiranje slajdova - :dir", "backgroundSlide": "Pozadina slajda", "removeSlide": "Obriši slajd", "cloneSlide": "Dupliciraj slajd", "newSlide": "Novi slajd", "insertElement": ":type Klikni i povuci do željenog mjesta", "newKeyword": "Nova ključna riječ", "save": "Save", "confirmRemoveElement": "Jeste li sigurni da želite obrisati ovaj element?", "cancel": "Otkaži", "done": "Gotovo", "remove": "Obriši", "edit": "Uredi", "keywordsTip": "Pomoć za ključne riječi.", "loading": "Učitava se...", "element": "Element", "resetToDefault": "Vratiti na zadane postavke", "resetToTemplate": "Vratiti na zadane postavke templejta", "slideBackground": "Pozadina", "setImageBackground": "Postavi kao pozadinu", "setColorFillBackground": "Postavi boju pozadine ", "activeSurfaceWarning": "Jeste li sigurni da želite aktivirati površinski modus? Ovaj postupak se ne može vratiti nazad.", "template": "Template", "templateDescription": "Biće primjenjeno za sve slajdove, a ne samo za \\":currentSlide\\" ", "currentSlide": "Trenutni slajd", "currentSlideDescription": "Biće primjenjeno samo na ovaj slajd, dok će svi drugi slajdovi u \\":template\\" ostati nepromjenjeni.", "slides": "SliSlajdovides", "showTitles": "Prikaži nazive", "alwaysShow": "Uvijek prikaži", "autoHide": "Uvijek sakrij", "ok": "OK", "slide": "Slide", "opacity": "Zamućenost", "goToSlide": "Go to slide", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Close navigation"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'ca'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'ca',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Confirmeu que voleu suprimir aquesta diapositiva?", "sortSlide": "Mou la diapositiva :dir", "backgroundSlide": "Fons de la diapositiva", "removeSlide": "Suprimeix la diapositiva", "cloneSlide": "Clona la diapositiva", "newSlide": "Afegeix una diapositiva", "insertElement": "Feu clic i arrossegueu per col·locar :type", "newKeyword": "Paraula clau nova", "save": "Desa", "confirmRemoveElement": "Confirmeu que voleu suprimir aquest element?", "cancel": "Cancel·la", "done": "Fet", "remove": "Suprimeix", "edit": "Edita", "keywordsTip": "Arrossegueu paraules clau utilitzant els dos botons que hi ha a dalt.", "loading": "S’està carregant...", "slides": "Diapositives", "element": "Element", "resetToDefault": "Restableix al valor predeterminat", "resetToTemplate": "Restableix a la plantilla", "slideBackground": "Fons de la diapositiva", "setImageBackground": "Imatge de fons", "setColorFillBackground": "Emplenament de color de fons", "activeSurfaceWarning": "Confirmeu que voleu activar el Mode de superfície activa? Aquesta acció no es pot desfer.", "template": "Plantilla", "templateDescription": "S’aplicarà a totes les diapositives que no se substitueixin per la configuració de \\":currentSlide\\".", "currentSlide": "Aquesta diapositiva", "currentSlideDescription": "Només s’aplicarà a aquesta diapositiva i substituirà qualsevol opció de configuració de \\":template\\".", "showTitles": "Mostra els títols", "alwaysShow": "Mostra sempre", "autoHide": "Amaga automàticament", "ok": "D’acord", "slide": "Diapositiva", "opacity": "Opacitat", "goToSlide": "Ves a la diapositiva", "expandBreadcrumbButtonLabel": "Enrere", "collapseBreadcrumbButtonLabel": "Tanca la navegació"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'cs'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'cs',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Opravdu chcete odstranit tento snímek?", "sortSlide": "Přesunout snímek :dir", "backgroundSlide": "Pozadí snímku", "removeSlide": "Odstranit snímek", "cloneSlide": "Klonovat snímek", "newSlide": "Přidat nový snímek", "insertElement": "Klepnutím a tažením umístěte :type", "newKeyword": "Nové klíčové slovo", "save": "Uložit", "confirmRemoveElement": "Opravdu chcete tento prvek smazat?", "cancel": "Zrušit", "done": "Hotovo", "remove": "Odstranit", "edit": "Upravit", "keywordsTip": "Přetáhněte klíčová slova pomocí dvou výše uvedených tlačítek.", "loading": "Nahrávání...", "slides": "Snímky", "element": "Prvek", "resetToDefault": "Obnovit výchozít", "resetToTemplate": "Obnovit na šablonu", "slideBackground": "Pozadí snímku", "setImageBackground": "Obrázek pozadí", "setColorFillBackground": "Barva výplně pozadí", "activeSurfaceWarning": "Opravdu chcete aktivovat režim aktivního povrchu? Tuto akci nelze vrátit zpět.", "template": "Šablona", "templateDescription": "Použije se na všechny snímky, které nejsou přepsány žádným nastavením \\":currentSlide\\" .", "currentSlide": "Tento snímek", "currentSlideDescription": "Bude použito pouze na tento snímek a přepíše všechna nastavení \\":template\\" .", "showTitles": "Zobrazit nadpisy", "alwaysShow": "Vždy zobrazit", "autoHide": "Vždy skrýt", "ok": "OK", "slide": "Snímek", "opacity": "Průhlednost", "goToSlide": "Přejít na snímek", "expandBreadcrumbButtonLabel": "Jít zpět", "collapseBreadcrumbButtonLabel": "Zavřít navigaci"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'de'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'de',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Diese Folie wirklich löschen?", "sortSlide": "Folie nach :dir verschieben", "backgroundSlide": "Folienhintergrund", "removeSlide": "Folie löschen", "cloneSlide": "Folie duplizieren", "newSlide": "Neue Folie", "insertElement": "Klicken und an die gewünschte Stelle ziehen, um :type zu platzieren", "newKeyword": "Neues Stichwort", "save": "Speichern", "confirmRemoveElement": "Dieses Element wirklich löschen?", "cancel": "Abbrechen", "done": "Fertig", "remove": "Entfernen", "edit": "Bearbeiten", "keywordsTip": "Ziehe Stichworte mit Hilfe der beiden oberen Buttons hinein.", "loading": "Lädt...", "element": "Element", "resetToDefault": "Auf Standard zurücksetzen", "resetToTemplate": "Auf Folienmaster zurücksetzen", "slideBackground": "Folienhintergrund", "setImageBackground": "Bild als Hintergrund", "setColorFillBackground": "Farbe als Hintergrund", "activeSurfaceWarning": "Bist du sicher, dass du den \\"Active Surface Mode\\" aktivieren möchtest? Dies kann nicht rückgängig gemacht werden.", "template": "Folienmaster", "templateDescription": "Gilt für alle Folien, für die keine gesonderte Einstellung unter \\":currentSlide\\" vorgenommen wurde.", "currentSlide": "Diese Folie", "currentSlideDescription": "Gilt nur für diese Folie und macht die Einstellungen unter \\":template\\" für sie bedeutungslos.", "slides": "Folien", "showTitles": "Folientitel anzeigen", "alwaysShow": "Immer anzeigen", "autoHide": "Automatisch verbergen", "ok": "Ok", "slide": "Folie", "opacity": "Deckkraft", "goToSlide": "Gehe zu Folie", "expandBreadcrumbButtonLabel": "Zurück", "collapseBreadcrumbButtonLabel": "Navigation schließen"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'el'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'el',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτή τη διαφάνεια;", "sortSlide": "Μετακίνηση διαφάνειας - :dir", "backgroundSlide": "Φόντο διαφάνειας", "removeSlide": "Διαγραφή διαφάνειας", "cloneSlide": "Αντιγραφή διαφάνειας", "newSlide": "Προσθήκη νέας διαφάνειας", "insertElement": "Κάντε κλικ και σύρετε για να τοποθετήσετε :type", "newKeyword": "Νέα λέξη-κλειδί", "save": "Αποθήκευση", "confirmRemoveElement": "Είστε σίγουροι ότι θέλετε να αφαιρέσετε αυτό το στοιχείο;", "cancel": "Ακύρωση", "done": "Ολοκλήρωση", "remove": "Αφαίρεση", "edit": "Επεξεργασία", "keywordsTip": "Σύρετε λέξεις-κλειδιά χρησιμοποιώντας τα δυο κουμπιά παραπάνω.", "loading": "Φόρτωση...", "slides": "Διαφάνειες", "element": "Στοιχείο", "resetToDefault": "Επαναφορά προεπιλογής", "resetToTemplate": "Επαναφορά προτύπου", "slideBackground": "Φόντο διαφάνειας", "setImageBackground": "Εικόνα φόντου", "setColorFillBackground": "Χρώμα γεμίσματος φόντου", "activeSurfaceWarning": "Είστε σίγουροι ότι θέλετε να ενεργοποιήσετε τη Λειτουργία Ενεργούς Επιφάνειας; Αυτή η ενέργεια δεν αναιρείται.", "template": "Πρότυπο", "templateDescription": "Θα εφαρμοστεί σε όλες τις διαφάνειες που δεν έχουν επηρεαστεί από ρυθμίσεις \\":currentSlide\\".", "currentSlide": "Αυτή η διαφάνεια", "currentSlideDescription": "Θα εφαρμοστεί μόνο σε αυτή τη διαφάνεια και θα γίνει αντικατάσταση των προεπιλεγμένων ρυθμίσεων \\":template\\".", "showTitles": "Εμφάνιση τίτλων", "alwaysShow": "Εμφάνιση πάντα", "autoHide": "Αυτόματη απόκρυψη", "ok": "Εντάξει", "slide": "Διαφάνεια", "opacity": "Διαφάνεια", "goToSlide": "Μετάβαση σε διαφάνεια", "expandBreadcrumbButtonLabel": "Πίσω", "collapseBreadcrumbButtonLabel": "Κλείσιμο πλοήγησης"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'en'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'en',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Are you sure you wish to delete this slide?", "sortSlide": "Move slide :dir", "backgroundSlide": "Slide background", "removeSlide": "Delete slide", "cloneSlide": "Clone slide", "newSlide": "Add new slide", "insertElement": "Click and drag to place :type", "newKeyword": "New keyword", "save": "Save", "confirmRemoveElement": "Are you sure you wish to delete this element?", "cancel": "Cancel", "done": "Done", "remove": "Delete", "edit": "Edit", "keywordsTip": "Drag in keywords using the two buttons above.", "loading": "Loading...", "slides": "Slides", "element": "Element", "resetToDefault": "Reset to default", "resetToTemplate": "Reset to template", "slideBackground": "Slide background", "setImageBackground": "Image background", "setColorFillBackground": "Color fill background", "activeSurfaceWarning": "Are you sure you want to activate Active Surface Mode? This action cannot be undone.", "template": "Template", "templateDescription": "Will be applied to all slides not overridden by any \\":currentSlide\\" settings.", "currentSlide": "This slide", "currentSlideDescription": "Will be applied to this slide only, and will override any \\":template\\" settings.", "showTitles": "Show titles", "alwaysShow": "Always show", "autoHide": "Auto hide", "ok": "OK", "slide": "Slide", "opacity": "Opacity", "goToSlide": "Go to slide", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Close navigation"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'es-mx'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'es-mx',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "¿Está seguro de querer eliminar esta página?", "sortSlide": "Mover página :dir", "backgroundSlide": "Fondo de la página", "removeSlide": "Eliminar página", "cloneSlide": "Clonar página", "newSlide": "Añadir página nueva", "insertElement": "Clic y arrastrar para colocar :type", "newKeyword": "Nueva palabra clave", "save": "Guardar", "confirmRemoveElement": "¿Está seguro de querer eliminar este elemento?", "cancel": "Cancelar", "done": "Hecho", "remove": "Eliminar", "edit": "Editar", "keywordsTip": "Arrastrar palabras clave usando los dos botones de arriba.", "loading": "Cargando...", "slides": "Páginas", "element": "Elemento", "resetToDefault": "Reiniciar a predeterminado", "resetToTemplate": "Reiniciar a plantilla", "slideBackground": "Fondo de la página", "setImageBackground": "Fondo de la imagen", "setColorFillBackground": "Relleno color del fondo", "activeSurfaceWarning": "¿Está seguro de querer activar el Modo de Superficie Activa? Esta acción no puede deshacerse.", "template": "Plantilla", "templateDescription": "Será aplicado a todas las páginas no anuladas por algunas configuraciones de \\":currentSlide\\".", "currentSlide": "Esta página", "currentSlideDescription": "Será aplicado solamente a esta página, y anulará cualquier configuración de \\":template\\".", "showTitles": "Mostrar títulos", "alwaysShow": "Mostrar siempre", "autoHide": "Auto ocultar", "ok": "Ok", "slide": "Página", "opacity": "Opacidad", "goToSlide": "Ir a página", "expandBreadcrumbButtonLabel": "Regresar", "collapseBreadcrumbButtonLabel": "Cerrar navegación"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'es'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'es',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "¿Seguro que quieres eliminar esta diapositiva?", "sortSlide": "Mover diapositiva :dir", "backgroundSlide": "Fondo de diapositiva", "removeSlide": "Eliminar diapositiva", "cloneSlide": "Clonar diapositiva", "newSlide": "Agregar nueva diapositiva", "insertElement": "Haz clic y arrastra para colocar :escriba", "newKeyword": "Nueva palabra clave", "save": "Guardar", "confirmRemoveElement": "¿Seguro de quieres eliminar este elemento?", "cancel": "Cancelar", "done": "Hecho", "remove": "Eliminar", "edit": "Editar", "keywordsTip": "Arrastrar palabras clave usando los dos botones de arriba.", "loading": "Cargando...", "slides": "Diapositivas", "element": "Elemento", "resetToDefault": "Restablecer a valores predeterminados", "resetToTemplate": "Restablecer a plantilla", "slideBackground": "Fondo de diapositiva", "setImageBackground": "Fondo de la imagen", "setColorFillBackground": "Relleno color del fondo", "activeSurfaceWarning": "¿Seguro que quieres activar el Modo de Superficie Activa? Esta acción no puede deshacerse.", "template": "Plantilla", "templateDescription": "Se aplicará a todas las diapositivas no anuladas por algún elemento de configuración de \\":currentSlide\\".", "currentSlide": "Esta diapositiva", "currentSlideDescription": "Se aplicará solo a esta diapositiva y anulará cualquier configuración de \\":template\\".", "showTitles": "Mostrar títulos", "alwaysShow": "Mostrar siempre", "autoHide": "Auto ocultar", "ok": "Ok", "slide": "Diapositiva", "opacity": "Opacidad", "goToSlide": "Ir a la diapositiva", "expandBreadcrumbButtonLabel": "Regresar", "collapseBreadcrumbButtonLabel": "Cerrar navegación"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'et'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'et',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Kas oled kindel, et soovid selle lehekülje kustutada?", "sortSlide": "Liiguta lehekülg :dir", "backgroundSlide": "Lehekülje taust", "removeSlide": "Kustuta lehekülg", "cloneSlide": "Klooni lehekülg", "newSlide": "Lisa uus lehekülg", "insertElement": "Asetamiseks kliki ja lohista :type", "newKeyword": "Uus võtmesõna", "save": "Salvesta", "confirmRemoveElement": "Kas oled kindel, et soovid selle elemendi eemaldada?", "cancel": "Tühista", "done": "Valmis", "remove": "Eemalda", "edit": "Töötle", "keywordsTip": "Lohista võtmesõnu, kasutades ülalolevaid kahte nuppu.", "loading": "Laadib...", "slides": "Leheküljed", "element": "Element", "resetToDefault": "Lähtesta vaikeseadetele", "resetToTemplate": "Lähtesta mallile", "slideBackground": "Lehekülje taust", "setImageBackground": "Pilt-taust", "setColorFillBackground": "Värvi-taust", "activeSurfaceWarning": "Kas oled kindel, et tahad aktiveerida Active Surface moodi? Seda tegevust ei saa tagasi võtta.", "template": "Mall", "templateDescription": "Kohaldatakse kõigile lehekülgedele, millel ei ole määratud  \\":currentSlide\\" seadeid.", "currentSlide": "See lehekülg", "currentSlideDescription": "Kohaldatakse vaid sellele leheküljele ja kohaldamisega kirjutatakse üle \\":template\\" seaded.", "showTitles": "Näita pealkirju", "alwaysShow": "Näita alati", "autoHide": "Peida automaatselt", "ok": "OK", "slide": "Lehekülg", "opacity": "Läbipaistvus", "goToSlide": "Mine leheküljele", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Sulge navigatsioon"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'eu'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'eu',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Ziur zaude ezabatu nahi duzula diapositiba hau?", "sortSlide": "Mugitu diapositiba :dir", "backgroundSlide": "Diapositibaren atzeko planoa", "removeSlide": "Kendu diapositiba", "cloneSlide": "Bikoiztu diapositiba", "newSlide": "Gehitu diapositiba berria", "insertElement": "Klikatu eta arrastatu kokalekura :type", "newKeyword": "Gako-hitz berria", "save": "Gorde", "confirmRemoveElement": "Ziur zaude kendu nahi duzula elementu hau?", "cancel": "Utzi", "done": "Eginda", "remove": "Kendu", "edit": "Editatu", "keywordsTip": "Arrastatu gako-hitzak goiko bi botoiak erabiliz.", "loading": "Kargatzen...", "slides": "Diapositibak", "element": "Elementua", "resetToDefault": "Berrezarri lehenetsia", "resetToTemplate": "Berrezarri txantiloia", "slideBackground": "Atzeko planoaren diapositiba", "setImageBackground": "Atzeko planoaren irudia", "setColorFillBackground": "Kolore betegarriko atzeko planoa", "activeSurfaceWarning": "Ziur zaude Surface modua aktibatu nahi duzula? Ekintza hori ezin da desegin.", "template": "Txantiloia", "templateDescription": "Aplikatuko da diapositiba guztietan \\":currentSlide\\" ezarpenen bidez baliogabetutakoak izan ezik.", "currentSlide": "Diapositiba hau", "currentSlideDescription": "Aplikatuko da soilik diapositiba honetan, eta baliogabetuko du edozein \\":template\\" ezarpena.", "showTitles": "Erakutsi tituluak", "alwaysShow": "Erakutsi beti", "autoHide": "Auto ezkutatu", "ok": "Ados", "slide": "Diapositiba", "opacity": "Opakutasuna", "goToSlide": "Joan diapositibara", "expandBreadcrumbButtonLabel": "Joan atzera", "collapseBreadcrumbButtonLabel": "Itxi nabigazioa"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'fi'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'fi',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Oletko varma että haluat poistaa tämän dian?", "sortSlide": "Siirrä diaa :dir", "backgroundSlide": "Dian taustakuva", "removeSlide": "Poista dia", "cloneSlide": "Kloonaa dia", "newSlide": "Lisää uusi dia", "insertElement": "Klikkaa ja raahaa paikalle :type", "newKeyword": "Uusi avainsana", "save": "Tallenna", "confirmRemoveElement": "Oletko varma että haluat poistaa tämän elementin?", "cancel": "Peruuta", "done": "Valmis", "remove": "Poista", "edit": "Editoi", "keywordsTip": "Raahaa avainsanat paikalleen käyttämällä yläpuolella olevia painikkeita", "loading": "Lataa...", "slides": "Diat", "element": "Elementti", "resetToDefault": "Palauta oletusasetuksille", "resetToTemplate": "Palauta aihion oletusasetuksille", "slideBackground": "Dian taustakuva", "setImageBackground": "Kuvan tausta", "setColorFillBackground": "Täytä tausta yhdellä värillä", "activeSurfaceWarning": "Haluatko varmasti ottaa käyttöön Active Surface-tilan? Tätä asetusta ei voi perua.", "template": "Aihio", "templateDescription": "Asetus tulee koskemaan kaikkia diasivuja joiden asetuksia ei yliajeta tällä hetkellä \\":currentSlide\\" asetuksilla.", "currentSlide": "Tämä dia", "currentSlideDescription": "Asetus tulee koskemaan vain nykyistä diaa ja se ylikirjoittaa kaikki \\":template\\" asetukset.", "showTitles": "Näytä otsikot", "alwaysShow": "Näytä sisällysluettelo aina", "autoHide": "Piilota automaattisesti", "ok": "OK", "slide": "Dia", "opacity": "Sisällysluettelon läpinäkyvyys", "goToSlide": "Siirry dialle", "expandBreadcrumbButtonLabel": "Paluu", "collapseBreadcrumbButtonLabel": "Sulje navigointi"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'fr'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'fr',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Êtes-vous sûr de vouloir supprimer cette diapositive ?", "sortSlide": "Tri des diapositives - :dir", "backgroundSlide": "Arrière plan de diapositive", "removeSlide": "Supprimer cette diapositive", "cloneSlide": "Dupliquer cette diapositive", "newSlide": "Ajouter une diapositive", "insertElement": "Cliquer ou glisser pour ajouter :type", "newKeyword": "Nouveau mot-clé", "save": "Enregistrer", "confirmRemoveElement": "Êtes-vous sûr de vouloir supprimer cet élément ?", "cancel": "Annuler", "done": "Valider", "remove": "Supprimer", "edit": "Editer", "keywordsTip": "Astuce mot-clé", "loading": "Chargement...", "element": "Element", "resetToDefault": "Réinitialiser à la valeur par défault", "resetToTemplate": "Réinitialiser à la valeur du modèle", "slideBackground": "Arrière plan de diapositive", "setImageBackground": "Arrière plan d\'image", "setColorFillBackground": "Couleur d\'arrière plan", "activeSurfaceWarning": "Êtes-vous sûr de vouloir activer le mode de surface active? Cette action ne peut pas être annulée.", "template": "Modèle", "templateDescription": "Sera appliqué à toutes les diapositives non personnalisées par les réglages de \\":currentSlide\\".", "currentSlide": "Cette diapositive", "currentSlideDescription": "Sera appliqué uniquement à cette diapositive, et remplacera tout réglage de \\":template\\".", "slides": "Diapositives", "showTitles": "Afficher les titres", "alwaysShow": "Toujours afficher", "autoHide": "Masquer automatiquement", "ok": "OK", "slide": "Diapositive", "opacity": "Opacité", "goToSlide": "Aller à la diapositive", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Close navigation"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'gl'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'gl',
                'translation' => json_encode(json_decode('{"libraryStrings": {"sortSlide": "Mover diapositiva :dir", "removeSlide": "Borrar diapositiva", "newSlide": "Engadir diapositiva nova", "newKeyword": "Nova palabra chave", "confirmRemoveElement": "Seguro que queres borrar este elemento?", "done": "Feito", "edit": "Editar", "loading": "Cargando...", "element": "Elemento", "resetToTemplate": "Restablecer ao modelo", "setImageBackground": "Fondo da imaxe", "activeSurfaceWarning": "Seguro que queres activar o Modo de Superficie Activa? Isto no se pode desfacer.", "templateDescription": "Aplicarase a todas as diapositivas non anuladas por calquera configuración \\":currentSlide\\".", "currentSlideDescription": "Aplicarase só a esta diapositiva e anulará calquera configuración \\":template\\".", "alwaysShow": "Amosar sempre", "ok": "OK", "opacity": "Opacidade", "expandBreadcrumbButtonLabel": "Volver", "confirmDeleteSlide": "Seguro que queres borrar esta diapositiva?", "save": "Gardar", "backgroundSlide": "Fondo da diapositiva", "cloneSlide": "Clonar diapositiva", "insertElement": "Preme e arrastra para colocar :type", "cancel": "Cancelar", "remove": "Borrar", "keywordsTip": "Arrastra para engadir palabras chave usando os dous botóns da parte superior.", "slides": "Diapositivas", "resetToDefault": "Restablecer a valor por defecto", "slideBackground": "Fondo da diapositiva", "setColorFillBackground": "Encher fondo de cor", "template": "Modelo", "currentSlide": "Esta diapositiva", "showTitles": "Amosar títulos", "autoHide": "Agachar automaticamente", "slide": "Diapositiva", "goToSlide": "Ir á diapositiva", "collapseBreadcrumbButtonLabel": "Pechar navegación"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'it'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'it',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Sei sicuro di voler eliminare questa slide?", "sortSlide": "Sposta la slide :dir", "backgroundSlide": "Sfondo della slide", "removeSlide": "Elimina slide", "cloneSlide": "Clona slide", "newSlide": "Aggiungi nuova slide", "insertElement": "Clicca e trascina per posizionare :type", "newKeyword": "Nuova parola chiave", "save": "Salva", "confirmRemoveElement": "Sei sicuro di voler eliminare questo elemento?", "cancel": "Cancella", "done": "Fatto", "remove": "Elimina", "edit": "Modifica", "keywordsTip": "Trascina le parole chiave usando i due pulsanti qui sopra.", "loading": "Caricamento in corso...", "slides": "Slide", "element": "Elemento", "resetToDefault": "Ripristina predefinito", "resetToTemplate": "Ripristina modello", "slideBackground": "Sfondo della slide", "setImageBackground": "Sfondo dell\'immagine", "setColorFillBackground": "Sfondo di riempimento a colori", "activeSurfaceWarning": "Sei sicuro di voler attivare l\'Active Surface Mode? Questa azione è irreversibile.", "template": "Modello", "templateDescription": "Sarà applicato a tutte le slide non sovrascritte da alcune delle impostazioni \\":currentSlide\\".", "currentSlide": "Questa slide", "currentSlideDescription": "Sarà applicato solo a questa slide, ma ne sovrascriverà tutte le impostazioni \\":template\\".", "showTitles": "Mostra titoli", "alwaysShow": "Mostra sempre", "autoHide": "Nascondi automaticamente", "ok": "Ok", "slide": "Slide", "opacity": "Opacità", "goToSlide": "Vai alla slide", "expandBreadcrumbButtonLabel": "Torna indietro", "collapseBreadcrumbButtonLabel": "Chiudi navigazione"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'ka'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'ka',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "დარწმუნებული ხართ, რომ ამ სლაიდის წაშლა გინდათ?", "sortSlide": "გადააადგილე სლაიდი :dir", "backgroundSlide": "სლაიდის ფონი", "removeSlide": "სლაიდის წაშლა", "cloneSlide": "სლაიდის კლონირება", "newSlide": "ახალი სლაიდის დამატება", "insertElement": "დააჭირე და გადაიტანე მოსათავსებლად :type", "newKeyword": "ახალი საკვანძო სიტყვა", "save": "შენახვა", "confirmRemoveElement": "დარწმუნებული ხართ, რომ ამ ელემენტის წაშლა გინდათ?", "cancel": "გაუქმება", "done": "შესრულებულია", "remove": "წაშლა", "edit": "რედაქტირება", "keywordsTip": "გადაიტანე საკვანძო სიტყვები ზემოთ მოცემული ორი ღილაკის გამოყენებით.", "loading": "იტვირთება...", "slides": "სლაიდები", "element": "ელემენტი", "resetToDefault": "დააბრუნე სტანდარტულზე", "resetToTemplate": "დააბრუნე შაბლონზე", "slideBackground": "სლაიდის ფონი", "setImageBackground": "სურათის ფონი", "setColorFillBackground": "ფონის ფერით შევსება", "activeSurfaceWarning": "დარწმუნებული ხართ, რომ გსურთ გაააქტიუროთ ზედაპირის რეჟიმის გააქტიურება? ამ ქმედებას უკან ვერ დააბრუნებთ.", "template": "შაბლონი", "templateDescription": "ყველა სლაიდზე ექნება ზემოქმედება.", "currentSlide": "ეს სლაიდი", "currentSlideDescription": "მხოლოდ ამ სლაიდზე იმოქმედებს და გადააწერს ნებისმიერ \\":template\\" პარამეტრს.", "showTitles": "აჩვენე სათაურები", "alwaysShow": "ყოველთვის აჩვენე", "autoHide": "ავტომატურად დამალე", "ok": "OK", "slide": "სლაიდი", "opacity": "გამჭვირვალობა", "goToSlide": "გადადი სლაიდზე", "expandBreadcrumbButtonLabel": "დაბრუნდი", "collapseBreadcrumbButtonLabel": "დახურე ნავიგაცია"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'km'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'km',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "តើអ្នកប្រាកដជាចង់លុបស្លាយនេះមែនទេ?", "sortSlide": "ផ្លាស់ទីស្លាយ :dir", "backgroundSlide": "ផ្ទៃខាងក្រោយស្លាយ", "removeSlide": "លុបស្លាយ", "cloneSlide": "ចម្លងស្លាយ", "newSlide": "បន្ថែមស្លាយថ្មី", "insertElement": "ឃ្លីកហើយអូសដើម្បីដាក់ :type", "newKeyword": "ពាក្យគន្លឹះថ្មី", "save": "រក្សាទុក", "confirmRemoveElement": "តើអ្នកប្រាកដជាចង់លុបធាតុនេះមែនទេ?", "cancel": "បោះបង់", "done": "រួចរាល់", "remove": "លុប", "edit": "កែ", "keywordsTip": "អូសបញ្ចូលពាក្យគន្លឹះដោយប្រើប៊ូតុងពីរខាងលើ។", "loading": "កំពុងផ្ទុក...", "slides": "ស្លាយ", "element": "ធាតុ", "resetToDefault": "ប្តូរទៅជាលំនាំដើម", "resetToTemplate": "ប្តូរទៅតាមពុម្ព", "slideBackground": "ផ្ទៃខាងក្រោយសម្រាប់ស្លាយ", "setImageBackground": "ផ្ទៃខាងក្រោយជារូបភាព", "setColorFillBackground": "ផ្ទៃខាងក្រោយជាពណ៌លាត", "activeSurfaceWarning": "តើអ្នកប្រាកដជាចង់បើកម៉ូត «Active Surface» មែនទេ? អ្នកមិនអាចត្រឡប់ក្រោយបានទេ។", "template": "ពុម្ព", "templateDescription": "នឹងអនុវត្តទៅលើស្លាយទាំងអស់ដែលមិនត្រូវបានរំលងដោយការកំណត់របស់ \\":currentSlide\\" ។", "currentSlide": "ស្លាយនេះ", "currentSlideDescription": "នឹងអនុវត្តទៅលើស្លាយនេះប៉ុណ្ណោះ ហើយនឹងរំលងលើការកំណត់ទាំងឡាយរបស់ \\":template\\" ។", "showTitles": "បង្ហាញចំណងជើង", "alwaysShow": "បង្ហាញរហូត", "autoHide": "លាក់ស្វ័យប្រវត្តិ", "ok": "អូខេ", "slide": "ស្លាយ", "opacity": "កម្រិតថ្លា", "goToSlide": "ទៅកាន់ស្លាយ", "expandBreadcrumbButtonLabel": "ត្រឡប់ក្រោយ", "collapseBreadcrumbButtonLabel": "បិទផ្ទាំងផ្លាស់ទី"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'ko'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'ko',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "이 슬라이드를 삭제하시겠습니까?", "sortSlide": "슬라이드 이동 :dir", "backgroundSlide": "슬라이드 배경", "removeSlide": "슬라이드 삭제", "cloneSlide": "슬라이드 복제", "newSlide": "새로운 슬라이드 추가", "insertElement": "클릭 후 드래그하여 이동 :type", "newKeyword": "새로운 키워드", "save": "저장", "confirmRemoveElement": "이 요소를 삭제하시겠습니까?", "cancel": "취소", "done": "완료", "remove": "삭제", "edit": "편집", "keywordsTip": "위 두 버튼을 사용하여 키워드로 끌어다 놓으십시오.", "loading": "로딩중...", "slides": "슬라이드", "element": "항목", "resetToDefault": "기본값으로 재설정", "resetToTemplate": "템플릿으로 재설정", "slideBackground": "슬라이드 배경", "setImageBackground": "이미지 배경", "setColorFillBackground": "색깔 채우기 배경", "activeSurfaceWarning": "Active Surface Mode를 활성화하시겠습니까? 이 실행은 되돌릴 수 없습니다.", "template": "템플릿", "templateDescription": "\\":currentSlide\\" 설정으로 재정의되지 않은 모든 슬라이드에 적용됨.", "currentSlide": "이 슬라이드", "currentSlideDescription": "이 슬라이드에만 적용되며 \\":template\\" 설정을 재정의함.", "showTitles": "제목 보이기", "alwaysShow": "항상 보이기", "autoHide": "자동 숨기기", "ok": "오케이", "slide": "슬라이드", "opacity": "투명도", "goToSlide": "슬라이드로 이동", "expandBreadcrumbButtonLabel": "돌아가기", "collapseBreadcrumbButtonLabel": "탐색 닫기"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'lt'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'lt',
                'translation' => json_encode(json_decode('{"libraryStrings": {"sortSlide": "Perkelti skaidrę :dir", "removeSlide": "Ištrinti skaidrę", "newSlide": "Pridėti naują skaidrę", "newKeyword": "Naujas raktinis žodis", "confirmRemoveElement": "Ar tikrai norite ištrinti šį elementą?", "done": "Atlikta", "edit": "Redaguoti", "loading": "Įkeliama...", "element": "Elementas", "resetToTemplate": "Iš naujo nustatyti šabloną", "setImageBackground": "Paveikslėlio fonas", "activeSurfaceWarning": "Ar tikrai norite suaktyvinti aktyvaus paviršiaus režimą? Šio veiksmo anuliuoti negalima.", "templateDescription": "Bus taikoma visoms skaidrėms, kurios nepakeistos jokių \\":currentSlide\\" nustatymų.", "currentSlideDescription": "Bus pritaikyta tik šiai skaidrei ir nepaisys visų „:template“ nustatymų.", "alwaysShow": "Visada rodyti", "ok": "Gerai", "opacity": "Permatomumas", "expandBreadcrumbButtonLabel": "Grįžti", "confirmDeleteSlide": "Ar tikrai norite ištrinti šią skaidrę?", "showTitles": "Rodyti pavadinimus", "backgroundSlide": "Skaidrės fonas", "cloneSlide": "Dubliuoti skaidrę", "insertElement": "Spustelėkite ir vilkite į vietą :type", "save": "Išsaugoti", "cancel": "Atšaukti", "remove": "Ištrinti", "keywordsTip": "Vilkite raktinius žodžius naudodami du aukščiau esančius mygtukus.", "slides": "Skaidrės", "resetToDefault": "Atstatyti į numatytuosius", "slideBackground": "Skaidrės fonas", "setColorFillBackground": "Spalvos užpildymo fonas", "template": "Šablonas", "currentSlide": "Ši skaidrė", "autoHide": "Automatiškai slėpti", "slide": "Skaidrė", "goToSlide": "Eiti į skaidrę", "collapseBreadcrumbButtonLabel": "Uždaryti navigaciją"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'lv'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'lv',
                'translation' => json_encode(json_decode('{"libraryStrings": {"template": "Šablons", "currentSlide": "Šis slaids", "newSlide": "Pievienot jaunu slaidu", "backgroundSlide": "Slaida fons", "removeSlide": "Dzēst slaidu", "newKeyword": "Jauns atslēgvārds", "save": "Saglabāt", "cancel": "Atcelt", "remove": "Dzēst", "edit": "Rediģēt", "keywordsTip": "Ievelciet atslēgvārdus izmantojot divas augstāk redzamās pogas.", "loading": "Ielādē...", "slides": "Slaidi", "element": "Elements", "resetToTemplate": "Atjaunot uz šablonu", "slideBackground": "Slaida fons", "setImageBackground": "Attēla fons", "currentSlideDescription": "Tiks pielietots tikai šim slaidam un pārrakstīs jebkādus \\":template\\" iestatījumus.", "showTitles": "Rādīt nosaukumus", "alwaysShow": "Vienmēr rādīt", "autoHide": "Automātiski paslēpt", "ok": "OK", "slide": "Slaids", "opacity": "Caurspīdīgums", "goToSlide": "Pāriet uz slaidu", "expandBreadcrumbButtonLabel": "Atgriezties", "collapseBreadcrumbButtonLabel": "Aizvērt navigāciju", "confirmDeleteSlide": "Vai esat pārliecināts, ka vēlaties dzēst šo slaidu?", "sortSlide": "Pārvietot slaidu :dir", "cloneSlide": "Dublēt slaidu", "insertElement": "Klikšķiniet un velciet, lai ievietotu :type", "confirmRemoveElement": "Vai esat pārliecināts, ka vēlaties dzēst šo elementu?", "resetToDefault": "Atjaunot uz noklusēto", "setColorFillBackground": "Krāsas aizpildījuma fons", "activeSurfaceWarning": "Vai esat pārliecināts, ka gribat aktivizēt Aktīvās Virsmas Režīmu? Šo darbību nevar atcelt.", "templateDescription": "Tiks piemērots visiem slaidiem, kuriem nav \\":currentSlide\\" iestatījumu.", "done": "Pabeigt"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'mn'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'mn',
                'translation' => json_encode(json_decode('{"libraryStrings": {"sortSlide": "Слайдыг зөөх :dir", "removeSlide": "Слайдыг устгах", "newSlide": "Шинэ слайд нэмэх", "newKeyword": "Шинэ түлхүүр үг", "confirmRemoveElement": "Та энэ элементийг устгахдаа итгэлтэй байна уу?", "done": "Дууслаа", "edit": "Засварлах", "loading": "Ачааж байна...", "element": "Элемент", "resetToTemplate": "Загвар руу дахин тохируулна уу", "setImageBackground": "Зургийн дэвсгэр", "activeSurfaceWarning": "Та идэвхтэй гадаргуугийн горимыг идэвхжүүлэхдээ итгэлтэй байна уу? Энэ үйлдлийг буцаах боломжгүй.", "templateDescription": "Ямар ч \\":currentSlide\\" тохиргоогоор дарагдаагүй бүх слайдад хэрэгжинэ.", "currentSlideDescription": "Зөвхөн энэ слайдад хэрэглэгдэх бөгөөд аливаа \\":template\\" тохиргоог хүчингүй болгоно.", "alwaysShow": "Үргэлж харуулах", "ok": "Сайн", "opacity": "Тунгалаг байдал", "expandBreadcrumbButtonLabel": "Буцах", "confirmDeleteSlide": "Та энэ слайдыг устгахдаа итгэлтэй байна уу?", "backgroundSlide": "Слайд дэвсгэр", "cloneSlide": "Слайдыг хувилах", "insertElement": "Байршуулахын тулд товшоод чирнэ үү :type", "save": "Хадгалах", "cancel": "Цуцлах", "remove": "Устгах", "keywordsTip": "Дээрх хоёр товчлуурыг ашиглан түлхүүр үгсийг чирнэ үү.", "slides": "Слайд", "resetToDefault": "Өгөгдмөл рүү дахин тохируулна уу", "slideBackground": "Слайд дэвсгэр", "setColorFillBackground": "Дэвсгэрт өнгө дүүргэх", "template": "Загвар", "currentSlide": "Энэ слайд", "showTitles": "Гарчиг харуулах", "autoHide": "Автоматаар нуух", "slide": "Слайд", "goToSlide": "Слайд руу оч", "collapseBreadcrumbButtonLabel": "Навигацыг хаах"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'nb'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'nb',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Er du sikker på at du vil slette denne sliden?", "sortSlide": "Flytt slide :dir", "backgroundSlide": "Bakgrunnsvelger", "removeSlide": "Slett slide", "cloneSlide": "Klon slide", "newSlide": "Legg til ny slide", "insertElement": "Klikk og dra for å plassere :type", "newKeyword": "Nytt nøkkelord", "save": "Lagre", "confirmRemoveElement": "Er du sikker på at du vil slette dette elementet?", "cancel": "Cancel", "done": "Done", "remove": "Slett", "edit": "Rediger", "keywordsTip": "Dra inn nøkkelord", "loading": "Laster...", "element": "Element", "resetToDefault": "Tilbakestill", "resetToTemplate": "Tilbakestill til mal", "slideBackground": "Bakgrunn", "setImageBackground": "Bildebakgrunn", "setColorFillBackground": "Fargebakgrunn", "activeSurfaceWarning": "Er du sikker på at du vil aktivere aktivoverflatemodus? Denne handlingen kan ikke gjøres om.", "template": "Mal", "templateDescription": "Innstillinger vil bli satt i alle slides some ikke er overskrevet av \\":currentSlide\\" innstillinger.", "currentSlide": "Denne sliden", "currentSlideDescription": "Innstillinger vil bli satt kun i denne sliden, og vil overskrive \\":template\\" innstillinger.", "slides": "Slides", "showTitles": "Vis titler", "alwaysShow": "Alltid vis", "autoHide": "Skjul automatisk", "ok": "OK", "slide": "Slide", "opacity": "Opasitet", "goToSlide": "Gå til slide", "expandBreadcrumbButtonLabel": "Gå tilbake", "collapseBreadcrumbButtonLabel": "Lukk navigasjon"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'nl'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'nl',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Weet je zeker dat je deze dia wilt verwijderen?", "sortSlide": "Verplaats dia :dir", "backgroundSlide": "Dia-achtergrond", "removeSlide": "Verwijder dia", "cloneSlide": "Kloon dia", "newSlide": "Voeg nieuwe dia toe", "insertElement": "Klik-en-sleep naar plaats :type", "newKeyword": "Nieuw trefwoord", "save": "Opslaan", "confirmRemoveElement": "Weet je zeker dat je dit element wilt verwijderen?", "cancel": "Annuleer", "done": "Klaar", "remove": "Verwijderen", "edit": "Bewerken", "keywordsTip": "Sleep trefwoorden met behulp van de twee knoppen hierboven.", "loading": "Aan het laden...", "slides": "Dia\'s", "element": "Element", "resetToDefault": "Herstellen naar standaard", "resetToTemplate": "Herstellen naar sjabloon", "slideBackground": "Dia-achtergrond", "setImageBackground": "Afbeelding achtergrond", "setColorFillBackground": "Opvulkleur achtergrond", "activeSurfaceWarning": "Weet je zeker dat je de \\"Active Surface Mode\\" wilt activeren? Deze actie kan niet ongedaan gemaakt worden.", "template": "Sjabloon", "templateDescription": "Wordt toegepast op alle dia\'s die niet overschreven worden door \\":currentSlide\\" instellingen.", "currentSlide": "Deze dia", "currentSlideDescription": "Wordt alleen op deze dia toegepast, en overschrijft \\":template\\" instellingen.", "showTitles": "Toon titels", "alwaysShow": "Altijd tonen", "autoHide": "Automatisch verbergen", "ok": "Ok", "slide": "Dia", "opacity": "Doorzichtigheid", "goToSlide": "Ga naar dia", "expandBreadcrumbButtonLabel": "Ga terug", "collapseBreadcrumbButtonLabel": "Sluit navigatie"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'nn'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'nn',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Er du sikker på at du vil slette dette skjermbiletet?", "sortSlide": "Flytt skjermbilete :dir", "backgroundSlide": "Bakgrunnsvelger", "removeSlide": "Slett skjermbilete", "cloneSlide": "Klon skjermbilete", "newSlide": "Legg til nytt skjermbilete", "insertElement": "Klikk og dra for å plassere :type", "newKeyword": "Nytt nøkkelord", "save": "Lagre", "confirmRemoveElement": "Er du sikker på at du vil slette dette elementet?", "cancel": "Cancel", "done": "Done", "remove": "Fjern", "edit": "Edit", "keywordsTip": "Dra inn nøkkelord", "loading": "Laster...", "element": "Element", "resetToDefault": "Tilbakestill", "resetToTemplate": "Tilbakestill til mal", "slideBackground": "Bakgrunn", "setImageBackground": "Bildebakgrunn", "setColorFillBackground": "Fargebakgrunn", "activeSurfaceWarning": "Er du sikker på at du vil aktivera aktivoverflatemodus? Denne handlinga kan ikkje angrast.", "template": "Mal", "templateDescription": "Innstillinger vil bli satt i alle slides some ikke er overskrevet av \\":currentSlide\\" innstillinger.", "currentSlide": "Dette skjermbilete", "currentSlideDescription": "Innstillinger vil bli satt kun i denne sliden, og vil overskrive \\":template\\" innstillinger.", "slides": "Slides", "showTitles": "Vis titler", "alwaysShow": "Alltid vis", "autoHide": "Skjul automatisk", "ok": "OK", "slide": "Skjermbilete", "opacity": "Opasitet", "goToSlide": "Gå til skjermbilete", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Close navigation"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'pl'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'pl',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Czy napewno chcesz usunąć ten slajd?", "sortSlide": "Przenieś slajd :dir", "backgroundSlide": "Tło slajdu", "removeSlide": "Usuń slajd", "cloneSlide": "Zduplikuj slajd", "newSlide": "Dodaj nowy slajd", "insertElement": "Kiknij i przesuń na miejsce :type", "newKeyword": "Nowe słowo kluczowe", "save": "Zapisz", "confirmRemoveElement": "Czy napewno chcesz usunąć ten element?", "cancel": "Anuluj", "done": "Gotowe", "remove": "Usuń", "edit": "Edytuj", "keywordsTip": "Przenieś słowa kluczowe używając dwóch przycisków powyżej.", "loading": "Ładowanie...", "slides": "Slajdy", "element": "Element", "resetToDefault": "Przywróć do ustawień domyślnych", "resetToTemplate": "Przywróć do ustawień szablonu", "slideBackground": "Tło slajdu", "setImageBackground": "Zdjęcie w tle", "setColorFillBackground": "Kolor tła", "activeSurfaceWarning": "Czy na pewno chcesz aktywować tryb powierzchni aktywnej? Tej czynności nie można cofnąć.", "template": "Szablon", "templateDescription": "Zostanie przypisane do wszystkich slajdów, które nie są nadpisane przez ustawienia tego slajdu \\":currentSlide\\".", "currentSlide": "Ten slajd", "currentSlideDescription": "Zostanie zastosowany tylko do tego slajdu. Nie wpłynie na ustawienia szablonu.", "showTitles": "Pokaż tytuły", "alwaysShow": "Zawsze pokazuj", "autoHide": "Ukrywaj automatycznie", "ok": "OK", "slide": "Slajd", "opacity": "Przezroczystość", "goToSlide": "Przejdź do slajdu", "expandBreadcrumbButtonLabel": "Wróć", "collapseBreadcrumbButtonLabel": "Zamknij nawigację"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'pt-br'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'pt-br',
                'translation' => json_encode(json_decode('{"libraryStrings": {"sortSlide": "Mover slide :dir", "removeSlide": "Excluir slide", "newSlide": "Adicionar novo slide", "newKeyword": "Nova palavra-chave", "confirmRemoveElement": "Você tem certeza de que deseja apagar este elemento?", "done": "Concluído", "edit": "Editar", "loading": "Carregando...", "element": "Elemento", "resetToTemplate": "Redefinir para o modelo", "setImageBackground": "Imagem de fundo", "activeSurfaceWarning": "Você tem certeza de que deseja ativar o Modo Superfície Ativa? Esta ação não pode ser desfeita.", "templateDescription": "Será aplicado a todos os slides não sobrepostos por nenhuma configuração \\":currentSlide\\".", "currentSlideDescription": "Será aplicado somente a este slide, e anulará qualquer configuração \\":template\\".", "alwaysShow": "Mostrar sempre", "ok": "OK", "opacity": "Opacidade", "expandBreadcrumbButtonLabel": "Voltar", "confirmDeleteSlide": "Você tem certeza de que deseja apagar este slide?", "backgroundSlide": "Fundo do Slide", "cloneSlide": "Duplicar slide", "insertElement": "Clique e arraste para colocar :type", "save": "Salvar", "cancel": "Cancelar", "remove": "Excluir", "keywordsTip": "Arraste em palavras-chave usando os dois botões acima.", "slides": "Slides", "resetToDefault": "Redefinir para o padrão", "slideBackground": "Fundo do Slide", "setColorFillBackground": "Fundo com preenchimento colorido", "template": "Modelo", "currentSlide": "Este slide", "showTitles": "Mostrar títulos", "autoHide": "Esconder automaticamente", "slide": "Slide", "goToSlide": "Ir para slide", "collapseBreadcrumbButtonLabel": "Fechar navegação"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'pt'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'pt',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Tem a certeza de que pretende apagar este slide?", "sortSlide": "Mover slide :dir", "backgroundSlide": "Fundo do slide", "removeSlide": "Apagar slide", "cloneSlide": "Duplicar slide", "newSlide": "Adicionar novo slide", "insertElement": "Clique e arraste para posicionar:type", "newKeyword": "Nova palavra-chave", "save": "Guardar", "confirmRemoveElement": "Tem a certeza de que pretende apagar este elemento?", "cancel": "Cancelar", "done": "Feito", "remove": "Apagar", "edit": "Editar", "keywordsTip": "Arrastrar palavras-chave usando os dois botões acima.", "loading": "Carregando...", "slides": "Diapositivos", "element": "Elemento", "resetToDefault": "Reiniciar para predefinição", "resetToTemplate": "Reiniciar para modelo", "slideBackground": "Fundo do slide", "setImageBackground": "Fundo da imagem", "setColorFillBackground": "Cor de preenchimento do fundo", "activeSurfaceWarning": "Tem a certeza de que pretende ativar o modo Active Surface? Esta ação não pode ser anulada.", "template": "Modelo", "templateDescription": "Será aplicado a todos os slides não personalizadas por qualquer configuração de \\":currentSlide\\".", "currentSlide": "Este slide", "currentSlideDescription": "Será aplicado apenas a este slide e substituirá qualquer configuração de \\":template\\".", "showTitles": "Mostrar títulos", "alwaysShow": "Mostrar sempre", "autoHide": "Ocultar automaticamente", "ok": "OK", "slide": "Slide", "opacity": "Opacidade", "goToSlide": "Ir para o slide", "expandBreadcrumbButtonLabel": "Retornar", "collapseBreadcrumbButtonLabel": "Fechar navegação"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'ro'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'ro',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Sunteți sigur că doriți să ștergeți acest diapozitiv?", "sortSlide": "Mută diapozitivul :dir", "backgroundSlide": "Fundal diapozitiv", "removeSlide": "Șterge diapozitivul", "cloneSlide": "Clonează diapozitivul", "newSlide": "Adaugă diapozitiv nou", "insertElement": "Apasă și glisează pentru a plasa :type", "newKeyword": "Cuvânt cheie nou", "save": "Salvează", "confirmRemoveElement": "Sunteți sigur că doriți să ștergeți acest element?", "cancel": "Anulează", "done": "Gata", "remove": "Șterge", "edit": "Editează", "keywordsTip": "Glisează cuvinte cheie folosind cele două butoane de mai sus.", "loading": "Se încarcă...", "slides": "Diapozitive", "element": "Element", "resetToDefault": "Resetează la valorile implicite", "resetToTemplate": "Resetează la șablon", "slideBackground": "Fundal diapozitiv", "setImageBackground": "Fundal imagine", "setColorFillBackground": "Fundal cu umplere de culoare", "activeSurfaceWarning": "Sunteți sigur că doriți să activați Modul Suprafață Activă? Această acțiune nu poate fi anulată.", "template": "Șablon", "templateDescription": "Se va aplica tuturor diapozitivelor care nu sunt suprascrise de setările pentru \\":currentSlide\\".", "currentSlide": "Acest diapozitiv", "currentSlideDescription": "Se va aplica doar acestui diapozitiv și va suprascrie orice setări de \\":template\\".", "showTitles": "Afișează titlurile", "alwaysShow": "Afișează mereu", "autoHide": "Ascunde automat", "ok": "OK", "slide": "Diapozitiv", "opacity": "Opacitate", "goToSlide": "Mergi la diapozitiv", "expandBreadcrumbButtonLabel": "Înapoi", "collapseBreadcrumbButtonLabel": "Închide navigarea"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'ru'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'ru',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Вы уверены, что хотите удалить этот слайд?", "sortSlide": "Переместить слайд :dir", "backgroundSlide": "Фон слайда", "removeSlide": "Удалить слайд", "cloneSlide": "Дублировать слайд", "newSlide": "Добавить новый слайд", "insertElement": "Нажмите и перетащите на место :type", "newKeyword": "Новое ключевое слово", "save": "Сохранить", "confirmRemoveElement": "Вы уверены, что хотите удалить этот элемент?", "cancel": "Отмена", "done": "Готово", "remove": "Удалить", "edit": "Изменить", "keywordsTip": "Перетащите ключевые слова, используя две кнопки выше.", "loading": "Загрузка...", "slides": "Слайды", "element": "Элемент", "resetToDefault": "Сбросить по умолчанию", "resetToTemplate": "Сбросить к шаблону", "slideBackground": "Фоновый цвет слайда", "setImageBackground": "Фоновое изображение", "setColorFillBackground": "Цвет заливки фона", "activeSurfaceWarning": "Вы уверены, что хотите активировать активный режим поверхности? Это действие не может быть отменено.", "template": "Template", "templateDescription": "Будет применяться ко всем слайдам не переопределяется любыми настройками \\":currentSlide\\".", "currentSlide": "Этот слайд", "currentSlideDescription": "Будет применяться только к этому слайду, и переопределит любые настройки \\":template\\".", "showTitles": "Показать названия", "alwaysShow": "Всегда показывать", "autoHide": "Автоматически скрывать", "ok": "OK", "slide": "Слайд", "opacity": "Непрозрачность", "goToSlide": "Перейти к слайду", "expandBreadcrumbButtonLabel": "Вернуться назад", "collapseBreadcrumbButtonLabel": "Закрыть навигацию"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'sl'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'sl',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Resnično izbrišem izbrano stran?", "sortSlide": "Premakni stran :dir", "backgroundSlide": "Ozadje strani", "removeSlide": "Izbriši stran", "cloneSlide": "Podvoji stran", "newSlide": "Dodaj novo stran", "insertElement": "S klikom postavi aktivnost :type", "newKeyword": "Nova ključna beseda", "save": "Shrani", "confirmRemoveElement": "Resnično izbrišem izbran element?", "cancel": "Prekliči", "done": "Potrdi", "remove": "Izbriši", "edit": "Uredi", "keywordsTip": "Povleci ključno besedo z zgornjima gumboma.", "loading": "Nalagam ...", "slides": "Strani", "element": "Element", "resetToDefault": "Ponastavi na privzeto", "resetToTemplate": "Ponastavi na predlogo", "slideBackground": "Ozadje strani", "setImageBackground": "Slika ozadja", "setColorFillBackground": "Ozadje zapolni z barvo", "activeSurfaceWarning": "Resnično preklopim v način z aktivno površino, ki skrije navigacijsko vrstico? Nastavitve ni možno preklicati.", "template": "Predloga", "templateDescription": "Nastavitev velja za vse strani in je \\":currentSlide\\" ne more preglasiti.", "currentSlide": "Ta stran", "currentSlideDescription": "Nastavitev velja samo za to stran in preglasi tudi nastavitve pod \\":template\\".", "showTitles": "Prikaži naslove", "alwaysShow": "Prikazuj ves čas", "autoHide": "Samodejno skrij", "ok": "V redu", "slide": "Stran", "opacity": "Prosojnost", "goToSlide": "Pojdi na stran", "expandBreadcrumbButtonLabel": "Nazaj", "collapseBreadcrumbButtonLabel": "Zapri krmarjenje"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'sma'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'sma',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Are you sure you wish to delete this slide?", "sortSlide": "Move slide :dir", "backgroundSlide": "Slide background", "removeSlide": "Delete slide", "cloneSlide": "Clone slide", "newSlide": "Add new slide", "insertElement": "Click and drag to place :type", "newKeyword": "New keyword", "save": "Save", "confirmRemoveElement": "Are you sure you wish to delete this element?", "cancel": "Cancel", "done": "Done", "remove": "Delete", "edit": "Edit", "keywordsTip": "Drag in keywords using the two buttons above.", "loading": "Loading...", "slides": "Slides", "element": "Element", "resetToDefault": "Reset to default", "resetToTemplate": "Reset to template", "slideBackground": "Slide background", "setImageBackground": "Image background", "setColorFillBackground": "Color fill background", "activeSurfaceWarning": "Are you sure you want to activate Active Surface Mode? This action cannot be undone.", "template": "Template", "templateDescription": "Will be applied to all slides not overridden by any \\":currentSlide\\" settings.", "currentSlide": "This slide", "currentSlideDescription": "Will be applied to this slide only, and will override any \\":template\\" settings.", "showTitles": "Show titles", "alwaysShow": "Always show", "autoHide": "Auto hide", "ok": "OK", "slide": "Slide", "opacity": "Opacity", "goToSlide": "Go to slide", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Close navigation"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'sme'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'sme',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Are you sure you wish to delete this slide?", "sortSlide": "Move slide :dir", "backgroundSlide": "Slide background", "removeSlide": "Delete slide", "cloneSlide": "Clone slide", "newSlide": "Add new slide", "insertElement": "Click and drag to place :type", "newKeyword": "New keyword", "save": "Save", "confirmRemoveElement": "Are you sure you wish to delete this element?", "cancel": "Cancel", "done": "Done", "remove": "Delete", "edit": "Edit", "keywordsTip": "Drag in keywords using the two buttons above.", "loading": "Loading...", "slides": "Slides", "element": "Element", "resetToDefault": "Reset to default", "resetToTemplate": "Reset to template", "slideBackground": "Slide background", "setImageBackground": "Image background", "setColorFillBackground": "Color fill background", "activeSurfaceWarning": "Are you sure you want to activate Active Surface Mode? This action cannot be undone.", "template": "Template", "templateDescription": "Will be applied to all slides not overridden by any \\":currentSlide\\" settings.", "currentSlide": "This slide", "currentSlideDescription": "Will be applied to this slide only, and will override any \\":template\\" settings.", "showTitles": "Show titles", "alwaysShow": "Always show", "autoHide": "Auto hide", "ok": "OK", "slide": "Slide", "opacity": "Opacity", "goToSlide": "Go to slide", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Close navigation"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'smj'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'smj',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Are you sure you wish to delete this slide?", "sortSlide": "Move slide :dir", "backgroundSlide": "Slide background", "removeSlide": "Delete slide", "cloneSlide": "Clone slide", "newSlide": "Add new slide", "insertElement": "Click and drag to place :type", "newKeyword": "New keyword", "save": "Save", "confirmRemoveElement": "Are you sure you wish to delete this element?", "cancel": "Cancel", "done": "Done", "remove": "Delete", "edit": "Edit", "keywordsTip": "Drag in keywords using the two buttons above.", "loading": "Loading...", "slides": "Slides", "element": "Element", "resetToDefault": "Reset to default", "resetToTemplate": "Reset to template", "slideBackground": "Slide background", "setImageBackground": "Image background", "setColorFillBackground": "Color fill background", "activeSurfaceWarning": "Are you sure you want to activate Active Surface Mode? This action cannot be undone.", "template": "Template", "templateDescription": "Will be applied to all slides not overridden by any \\":currentSlide\\" settings.", "currentSlide": "This slide", "currentSlideDescription": "Will be applied to this slide only, and will override any \\":template\\" settings.", "showTitles": "Show titles", "alwaysShow": "Always show", "autoHide": "Auto hide", "ok": "OK", "slide": "Slide", "opacity": "Opacity", "goToSlide": "Go to slide", "expandBreadcrumbButtonLabel": "Go back", "collapseBreadcrumbButtonLabel": "Close navigation"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'sv'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'sv',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Är du säker på att du vill ta bort den här sidan?", "sortSlide": "Flytta sidan :dir", "backgroundSlide": "Sidans bakgrund", "removeSlide": "Ta bort sidan", "cloneSlide": "Klona sida", "newSlide": "Lägg till sida", "insertElement": "Klicka och dra för att placera ut :type", "newKeyword": "Nytt nyckelord", "save": "Spara", "confirmRemoveElement": "Är du säker att du vill ta bort denna komponent?", "cancel": "Avbryt", "done": "Färdig", "remove": "Radera", "edit": "Redigera", "keywordsTip": "Dra in nyckelord med de två knapparna ovanför.", "loading": "Laddar...", "slides": "Sidor", "element": "Komponent", "resetToDefault": "Återställ till standard", "resetToTemplate": "Återställ till mall", "slideBackground": "Sidans bakgrund", "setImageBackground": "Bildbakgrund", "setColorFillBackground": "Bakgrundsfärg", "activeSurfaceWarning": "Är du säker på att du vill aktivera Active Surface Mode? Den här åtgärden kan inte ångras.", "template": "Mall", "templateDescription": "Kommer tillämpas på alla sidor som inte har någon \\":currentSlide\\" inställning.", "currentSlide": "Denna sida", "currentSlideDescription": "Kommer bara tillämpas på denna sida och \\":template\\" inställningarna skrivs över.", "showTitles": "Visa rubrikerna", "alwaysShow": "Visa alltid", "autoHide": "Dölj automatiskt", "ok": "OK", "slide": "Sida", "opacity": "Transparens", "goToSlide": "Gå till sida", "expandBreadcrumbButtonLabel": "Gå tillbaka", "collapseBreadcrumbButtonLabel": "Stäng navigering"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'sw'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'sw',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Una uhakika ungependa kufuta slaidi hii?", "sortSlide": "Sogeza slaidi:dir", "backgroundSlide": "Mandhari nyuma ya slaidi", "removeSlide": "Futa slaidi", "cloneSlide": "Iongeze slaidi", "newSlide": "Ongeza slaidi mpya", "insertElement": "Bofya na uburute mahali:type", "newKeyword": "Neno muhimu jipya", "save": "Hifadhi", "confirmRemoveElement": "Una uhakika ungependa kufuta kipengele hiki?", "cancel": "Ghairi", "done": "Imekamilika", "remove": "Futa", "edit": "Hariri", "keywordsTip": "Buruta maneno muhimu kwa kutumia vitufe viwili hapo juu.", "loading": "Inapakia...", "slides": "Slaidi", "element": "Kipengele", "resetToDefault": "Weka upya kwa chaguo-msingi", "resetToTemplate": "Weka upya kwa kiolezo", "slideBackground": "Mandhari nyuma ya slaidi", "setImageBackground": "Mandharinyuma ya picha", "setColorFillBackground": "Mandharinyuma ya kujaza rangi", "activeSurfaceWarning": "Una uhakika unataka kuwezesha Njia ya Uso Amilifu? Kitendo hiki hakiwezi kutenduliwa.", "template": "Kiolezo", "templateDescription": "Itatumika kwa slaidi zote ambazo hazijabatilishwa na mipangilio yoyote \\":currentSlide\\".", "currentSlide": "Slaidi hii", "currentSlideDescription": "Itatumika kwa slaidi hii pekee, na itabatilisha mipangilio \\":template\\" yoyote.", "showTitles": "Onyesha mada", "alwaysShow": "Onyesha kila wakati", "autoHide": "Ficha kiotomatiki", "ok": "SAWA", "slide": "Slaidi", "opacity": "Uwazi", "goToSlide": "Nenda kwenye slaidi", "expandBreadcrumbButtonLabel": "Nenda nyuma", "collapseBreadcrumbButtonLabel": "Funga urambazaji"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'te'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'te',
                'translation' => json_encode(json_decode('{"libraryStrings": {"sortSlide": "స్లయిడ్‌ని తరలించు :dir", "removeSlide": "స్లయిడ్‌ను తొలగించండి", "newSlide": "కొత్త స్లయిడ్‌ని జోడించండి", "newKeyword": "కొత్త కీవర్డ్", "confirmRemoveElement": "మీరు ఖచ్చితంగా ఈ ఎలిమెంట్ ను తొలగించాలనుకుంటున్నారా?", "done": "పూర్తి అయ్యింది", "edit": "సవరించు", "loading": "లోడింగ్...", "element": "ఎలిమెంట్", "resetToTemplate": "టెంప్లేట్‌కి రీసెట్ చేయండి", "setImageBackground": "ఇమేజ్ బ్యాక్ గ్రౌండ్", "activeSurfaceWarning": "మీరు ఖచ్చితంగా యాక్టివ్ సర్ఫేస్ మోడ్‌ని యాక్టివేట్ చేయాలనుకుంటున్నారా? ఈ చర్యను తిరిగి వెనక్కి తీసుకోలేరు.", "templateDescription": "\\":currentSlide\\" సెట్టింగ్ లు ఓవర్ రైడ్ చేయకుండా అన్ని స్లయిడ్‌లకు వర్తిస్తాయి.", "currentSlideDescription": "ఈ స్లయిడ్‌కు మాత్రమే వర్తించబడుతుంది మరియు \\":template\\" సెట్టింగ్‌లను ఓవర్ రైడ్ చేస్తుంది.", "alwaysShow": "ఎల్లప్పుడూ చూపించు", "ok": "అలాగే", "opacity": "ఒపాసిటీ", "expandBreadcrumbButtonLabel": "వెనక్కి వెళ్ళు", "confirmDeleteSlide": "మీరు ఖచ్చితంగా ఈ స్లయిడ్‌ని తొలగించాలనుకుంటున్నారా?", "backgroundSlide": "స్లయిడ్ బ్యాక్ గ్రౌండ్", "cloneSlide": "క్లోన్ స్లయిడ్", "insertElement": "క్లిక్ చేసి ఆ ప్లేస్ కి లాగండి :type", "save": "సేవ్ చేయండి", "cancel": "కేన్సిల్", "remove": "తొలగించు", "keywordsTip": "పైన ఉన్న రెండు బటన్‌లను ఉపయోగించి కీలకపదాలను డ్రాగ్ చేయండి.", "slides": "స్లయిడ్‌లు", "resetToDefault": "డిఫాల్ట్ కు రీసెట్ చెయ్యి", "slideBackground": "స్లయిడ్ బ్యాక్ గ్రౌండ్", "setColorFillBackground": "రంగుతో కూడిన బ్యాక్ గ్రౌండ్", "template": "టెంప్లేట్", "currentSlide": "ఈ స్లయిడ్", "showTitles": "శీర్షికలను చూపించు", "autoHide": "ఆటో హైడ్", "slide": "స్లయిడ్", "goToSlide": "స్లయిడ్‌కి వెళ్ళు", "collapseBreadcrumbButtonLabel": "నావిగేషన్‌ను మూసివేయండి"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'tr'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'tr',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "Bu slaydı silmek istediğinizden emin misiniz?", "sortSlide": ":dir slaydını taşı", "backgroundSlide": "Slayt arka planı", "removeSlide": "Slaydı sil", "cloneSlide": "Slaytı klonla", "newSlide": "Yeni slayt ekle", "insertElement": ":type alanına yerleştirmek için tıklayın ve sürükleyin", "newKeyword": "Yeni anahtar kelime", "save": "Kaydet", "confirmRemoveElement": "Bu öğeyi silmek istediğinize emin misiniz?", "cancel": "İptal", "done": "Tamamlandı", "remove": "Silmek", "edit": "Düzenlemek", "keywordsTip": "Yukarıdaki iki düğmeyi kullanarak anahtar kelimeleri sürükleyin.", "loading": "Yükleniyor...", "slides": "Slaytlar", "element": "Eleman", "resetToDefault": "Varsayılana sıfırla", "resetToTemplate": "Şablona sıfırla", "slideBackground": "Slayt arka planı", "setImageBackground": "Görüntü arka planı", "setColorFillBackground": "Renk dolgusu arka planı", "activeSurfaceWarning": "Aktif Yüzey Modunu etkinleştirmek istediğinizden emin misiniz? Bu işlem geri alınamaz.", "template": "Şablon", "templateDescription": "\\":currentSlide\\" ayarı herhangi bir slayt tarafından geçersiz kılınamayacak şekilde tüm slaytlara uygulanacaktır.", "currentSlide": "Bu slayt", "currentSlideDescription": "Yalnızca bu slayda uygulanacak ve tüm \\":template\\" ayarlarını geçersiz kılacaktır.", "showTitles": "Başlıkları göster", "alwaysShow": "Her zaman göster", "autoHide": "Otomatik Gizle", "ok": "Tamam", "slide": "Slayt", "opacity": "Opaklık", "goToSlide": "Slayta git", "expandBreadcrumbButtonLabel": "Geri git", "collapseBreadcrumbButtonLabel": "Gezinmeyi kapat"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'zh-cn'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'zh-cn',
                'translation' => json_encode(json_decode('{"libraryStrings": {"edit": "编辑", "keywordsTip": "使用上面的两个按钮拖动关键字。", "loading": "加载中...", "slides": "幻灯片", "element": "元素", "confirmDeleteSlide": "您确定要删除这张幻灯片吗?", "sortSlide": "移动幻灯片:dir", "backgroundSlide": "幻灯片背景", "removeSlide": "删除幻灯片", "cloneSlide": "克隆的幻灯片", "newSlide": "添加新幻灯片", "insertElement": "单击并拖动到指定位置:键入", "newKeyword": "新的关键字", "save": "保存", "confirmRemoveElement": "您确定要删除此元素吗?", "cancel": "取消", "done": "完成", "remove": "删除", "resetToDefault": "恢复默认设置", "resetToTemplate": "重置为模板", "slideBackground": "幻灯片背景", "setImageBackground": "图像背景", "setColorFillBackground": "颜色填充背景", "activeSurfaceWarning": "您确定要激活活动表面模式吗?此操作不能撤消。", "template": "模版", "templateDescription": "将应用于所有未被任何“:currentSlide”设置覆盖的幻灯片。", "currentSlide": "此幻灯片", "currentSlideDescription": "将仅应用于此幻灯片，并将覆盖任何“:template”设置。", "showTitles": "显示标题", "alwaysShow": "总是显示", "autoHide": "自动隐藏", "ok": "OK", "slide": "幻灯片", "opacity": "透明度", "goToSlide": "转到幻灯片", "expandBreadcrumbButtonLabel": "返回", "collapseBreadcrumbButtonLabel": "关闭导航"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }

        $existingLang = DB::table('h5p_libraries_languages')->where(['library_id' => $libId, 'language_code' => 'zh'])->first();
        if (empty($existingLang)) {
            DB::table('h5p_libraries_languages')->insert([
                'library_id' => $libId,
                'language_code' => 'zh',
                'translation' => json_encode(json_decode('{"libraryStrings": {"confirmDeleteSlide": "確定要刪除這個投影片？", "sortSlide": "投影片排序 - :dir", "backgroundSlide": "投影片背景", "removeSlide": "移除此投影片", "cloneSlide": "複製此投影片", "newSlide": "添加新投影片", "insertElement": "点击并拖拽以添加 :type", "newKeyword": "新增關鍵字", "save": "儲存", "confirmRemoveElement": "確定要移除這個元素？", "cancel": "取消", "done": "完成", "remove": "移除", "edit": "編輯", "keywordsTip": "關鍵字提示", "loading": "正在加载...", "element": "元素", "resetToDefault": "重置成預設值", "resetToTemplate": "重置成範本", "slideBackground": "投影片背景", "setImageBackground": "背景圖片", "setColorFillBackground": "背景顏色", "activeSurfaceWarning": "確定要啟用活動表面模式嗎？一旦啟用就無法撤銷喔。", "template": "範本", "templateDescription": "將套用於所有非自訂投影片 \\":currentSlide\\".", "currentSlide": "當前投影片", "currentSlideDescription": "僅套用於此幻燈片，並將覆蓋任何設置 \\":template\\".", "slides": "投影片", "showTitles": "顯示標題", "alwaysShow": "永遠顯示", "autoHide": "自動隱藏", "ok": "確定", "slide": "投影片", "opacity": "不透明度", "goToSlide": "移至投影片", "expandBreadcrumbButtonLabel": "返回", "collapseBreadcrumbButtonLabel": "关闭导航"}}'), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)
            ]);
        }
    }
}
