name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Deploy
        run: |
            cd /home/githubrunner/framework-api
            git pull
            docker build -t currikiprod-api .

            echo "Updating Docker Swarm Stack..."
            # Updating Server
            # docker service update --force --image currikiprod-api:latest currikistack_currikiprod-api
            
            
            
