name: Deploy to Linode

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Deploy
        run: |
            cd /home/githubrunner/framework-api
            git pull
            docker build -t currikiprod-api -f Dockerfile.8.1 .
            docker tag currikiprod-api quay.io/curriki/api:frame-new
            docker push quay.io/curriki/api:frame-new

            docker build -t currikiprod-cron -f Dockerfile.cron.8.1 .
            docker tag currikiprod-cron quay.io/curriki/api:frame-cron-new
            docker push quay.io/curriki/api:frame-cron-new

            echo "Updating Docker Swarm Stack..."
            # Updating Server
            docker service update --image quay.io/curriki/api:frame-new currikistack_currikiprod-migrate
            docker service update --image quay.io/curriki/api:frame-new currikistack_currikiprod-api
            docker service update --image quay.io/curriki/api:frame-new currikistack_currikiprod-queue
            docker service update --image quay.io/curriki/api:frame-cron-new currikistack_currikiprod-cron




